Repository optidatacloud/vue-advanced-chat, pull requests merged in 2024-04, with the labels that each got.

#58 feat: archived rooms indicator (issue #57, pr #58)
  README.md
  dist/vue-advanced-chat.es.js
  dist/vue-advanced-chat.umd.js
  src/components/SvgIcon/SvgIcon.vue
  src/lib/ChatWindow.vue
  src/lib/RoomsList/RoomsList.scss
  src/lib/RoomsList/RoomsList.vue
Labels: enhancement

#65 feat: Emits event when user clicks on message username (issue #62)
  README.md
  docs/username-on-message.png
  src/lib/ChatWindow.vue
  src/lib/Room/Room.vue
  src/lib/Room/RoomMessage/RoomMessage.vue
Labels: enhancement

#64 fix: adds fallback condition text (issue #63)
  dist/vue-advanced-chat.es.js
  dist/vue-advanced-chat.umd.js
  src/lib/Room/RoomHeader/RoomHeader.vue
  src/lib/RoomsList/RoomsList.vue
Labels: :no_entry: no-test

#67 chore: Update our VAC with upstream changes
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/build.yml
  .github/workflows/release.yml
  .gitignore
  .releaserc.yml
  README.md
  demo/deploy.sh
  demo/package.json
  demo/src/App.vue
  dist/vue-advanced-chat.es.js
  dist/vue-advanced-chat.umd.js
  package.json
  src/lib/ChatWindow.vue
  src/lib/Room/Room.vue
  src/lib/Room/RoomFooter/RoomFooter.vue
  src/lib/RoomsList/RoomContent/RoomContent.vue
  src/lib/RoomsList/RoomsList.scss
  tests/unit/mock-data.js
  types/index.d.ts
Labels: enhancement

#68 redo: read more indication for files and deleted messages (issue #59, pr # 68)
  src/lib/Room/RoomMessage/RoomMessage.vue
Labels: bug
